// Code generated by qtc from "autheps.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line autheps.sql:1
package autheps

//line autheps.sql:1
import . "github.com/0xor1/tlbx/pkg/core"

//line autheps.sql:2
import . "github.com/0xor1/tlbx/pkg/web/app/sql"

//line autheps.sql:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line autheps.sql:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line autheps.sql:4
func streamqryInsert(qw422016 *qt422016.Writer, args *sql.Args, auth *fullAuth) {
//line autheps.sql:4
	qw422016.N().S(`
`)
//line autheps.sql:5
	qw422016.N().S(` INSERT INTO auths (id, email, registeredOn, activatedOn, newEmail, activateCode, changeEmailCode, lastPwdResetOn, salt, pwd, n, r, p) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) `)
//line autheps.sql:36
	*args = sql.NewArgs(13)
	args.Append(
		auth.ID,
		auth.Email,
		auth.RegisteredOn,
		auth.ActivatedOn,
		auth.NewEmail,
		auth.ActivateCode,
		auth.ChangeEmailCode,
		auth.LastPwdResetOn,
		auth.Salt,
		auth.Pwd,
		auth.N,
		auth.R,
		auth.P,
	)

//line autheps.sql:51
	qw422016.N().S(` `)
//line autheps.sql:52
	qw422016.N().S(`
`)
//line autheps.sql:53
}

//line autheps.sql:53
func writeqryInsert(qq422016 qtio422016.Writer, args *sql.Args, auth *fullAuth) {
//line autheps.sql:53
	qw422016 := qt422016.AcquireWriter(qq422016)
//line autheps.sql:53
	streamqryInsert(qw422016, args, auth)
//line autheps.sql:53
	qt422016.ReleaseWriter(qw422016)
//line autheps.sql:53
}

//line autheps.sql:53
func qryInsert(args *sql.Args, auth *fullAuth) string {
//line autheps.sql:53
	qb422016 := qt422016.AcquireByteBuffer()
//line autheps.sql:53
	writeqryInsert(qb422016, args, auth)
//line autheps.sql:53
	qs422016 := string(qb422016.B)
//line autheps.sql:53
	qt422016.ReleaseByteBuffer(qb422016)
//line autheps.sql:53
	return qs422016
//line autheps.sql:53
}

//line autheps.sql:55
func streamqryGet(qw422016 *qt422016.Writer, args *sql.Args, email *string, id *ID) {
//line autheps.sql:55
	qw422016.N().S(`
`)
//line autheps.sql:56
	qw422016.N().S(` `)
//line autheps.sql:58
	PanicIf(email == nil && id == nil, "one of email or id must not be nil")
	*args = sql.NewArgs(1)

//line autheps.sql:59
	qw422016.N().S(` SELECT id, email, registeredOn, activatedOn, newEmail, activateCode, changeEmailCode, lastPwdResetOn, salt, pwd, n, r, p FROM auths WHERE `)
//line autheps.sql:76
	if email != nil {
//line autheps.sql:76
		qw422016.N().S(` email `)
//line autheps.sql:78
		args.AppendOne(*email)

//line autheps.sql:78
		qw422016.N().S(` `)
//line autheps.sql:79
	} else {
//line autheps.sql:79
		qw422016.N().S(` id `)
//line autheps.sql:81
		args.AppendOne(*id)

//line autheps.sql:81
		qw422016.N().S(` `)
//line autheps.sql:82
	}
//line autheps.sql:82
	qw422016.N().S(` = ? `)
//line autheps.sql:85
	qw422016.N().S(`
`)
//line autheps.sql:86
}

//line autheps.sql:86
func writeqryGet(qq422016 qtio422016.Writer, args *sql.Args, email *string, id *ID) {
//line autheps.sql:86
	qw422016 := qt422016.AcquireWriter(qq422016)
//line autheps.sql:86
	streamqryGet(qw422016, args, email, id)
//line autheps.sql:86
	qt422016.ReleaseWriter(qw422016)
//line autheps.sql:86
}

//line autheps.sql:86
func qryGet(args *sql.Args, email *string, id *ID) string {
//line autheps.sql:86
	qb422016 := qt422016.AcquireByteBuffer()
//line autheps.sql:86
	writeqryGet(qb422016, args, email, id)
//line autheps.sql:86
	qs422016 := string(qb422016.B)
//line autheps.sql:86
	qt422016.ReleaseByteBuffer(qb422016)
//line autheps.sql:86
	return qs422016
//line autheps.sql:86
}

//line autheps.sql:88
func streamqryUpdate(qw422016 *qt422016.Writer, args *sql.Args, auth *fullAuth) {
//line autheps.sql:88
	qw422016.N().S(`
`)
//line autheps.sql:89
	qw422016.N().S(` UPDATE auths SET email=?, registeredOn=?, activatedOn=?, newEmail=?, activateCode=?, changeEmailCode=?, lastPwdResetOn=?, salt=?, pwd=?, n=?, r=?, p=? WHERE id=? `)
//line autheps.sql:107
	*args = sql.NewArgs(13)
	args.Append(
		auth.Email,
		auth.RegisteredOn,
		auth.ActivatedOn,
		auth.NewEmail,
		auth.ActivateCode,
		auth.ChangeEmailCode,
		auth.LastPwdResetOn,
		auth.Salt,
		auth.Pwd,
		auth.N,
		auth.R,
		auth.P,
		auth.ID,
	)

//line autheps.sql:122
	qw422016.N().S(` `)
//line autheps.sql:123
	qw422016.N().S(`
`)
//line autheps.sql:124
}

//line autheps.sql:124
func writeqryUpdate(qq422016 qtio422016.Writer, args *sql.Args, auth *fullAuth) {
//line autheps.sql:124
	qw422016 := qt422016.AcquireWriter(qq422016)
//line autheps.sql:124
	streamqryUpdate(qw422016, args, auth)
//line autheps.sql:124
	qt422016.ReleaseWriter(qw422016)
//line autheps.sql:124
}

//line autheps.sql:124
func qryUpdate(args *sql.Args, auth *fullAuth) string {
//line autheps.sql:124
	qb422016 := qt422016.AcquireByteBuffer()
//line autheps.sql:124
	writeqryUpdate(qb422016, args, auth)
//line autheps.sql:124
	qs422016 := string(qb422016.B)
//line autheps.sql:124
	qt422016.ReleaseByteBuffer(qb422016)
//line autheps.sql:124
	return qs422016
//line autheps.sql:124
}
